### ISSUE TITLE
requirements.txt需重点添加qfluentwidgets相关组件

### ISSUE THREAD

**Issue by syunaht** [GALIAIS/LimbusCompanySRA#1]
其他缺少的库都好解决，就是这个库，装错了直接闪退，连报错都没有。
https://qfluentwidgets.com/zh/pages/install
> 请勿同时安装 PyQt-Fluent-Widgets、PyQt6-Fluent-Widgets、PySide2-Fluent-Widgets 和 PySide6-Fluent-Widgets，因为他们的包名都是 qfluentwidgets.
如果混用 PyQt 和 PySide，会导致程序直接闪退，遇到此问题请自行检查安装的组件库是否对应所使用的 PyQt/PySide。

安装轻量版
pip install PySide6-Fluent-Widgets -i https://pypi.org/simple/

安装完整版
pip install "PySide6-Fluent-Widgets[full]" -i https://pypi.org/simple/

由于不知道项目是否需要完整版组件，就没有提pr
感谢师傅的项目！

**Comment by GALIAIS** [comment]
> 其他缺少的库都好解决，就是这个库，装错了直接闪退，连报错都没有。 [https://qfluentwidgets.com/zh/pages/install ](https://qfluentwidgets.com/zh/pages/install)
> 
> > 请勿同时安装 PyQt-Fluent-Widgets、PyQt6-Fluent-Widgets、PySide2-Fluent-Widgets 和 PySide6-Fluent-Widgets，因为他们的包名都是 qfluentwidgets. 
> > 如果混用 PyQt 和 PySide，会导致程序直接闪退，遇到此问题请自行检查安装的组件库是否对应所使用的 PyQt/PySide。
> 
> 安装轻量版 pip install PySide6-Fluent-Widgets -i [ https://pypi.org/simple/ ](https://pypi.org/simple/)
> 
> 安装完整版 pip install "PySide6-Fluent-Widgets[full]" -i [ https://pypi.org/simple/ ](https://pypi.org/simple/)
> 
> 由于不知道项目是否需要完整版组件，就没有提pr 感谢师傅的项目！

感谢反馈,已将依赖加入requirements.txt
