### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by syunaht** [GALIAIS/LimbusCompanySRA#2]
## 问题1
在类似以下界面(事件，boss中途事件)
![ebae1897adf5d99ba8cd499ae2b301b](https://github.com/user-attachments/assets/82d818d4-7585-4d50-be50-248f6fe37acd)
以及商店自动治疗完：
![55e0b7941187d119c61c392dba24aea](https://github.com/user-attachments/assets/df6fd64f-cd90-4c21-be09-8b92db212d78)
都会卡住
## 问题2
进入镜牢的时候默认选择困难镜牢，是有相关设置吗
## 问题3
以及readme中，python3.11+应该修改为3.12+，项目中使用了3.11不支持的语法：
`f"{cfgm.get("Mirror_Dungeons.mirror_loop_count")}"`

**Comment by GALIAIS** [comment]
**问题1**商店和休息点已解决，战斗部分需要单独判断的异想体事件会在之后更新加入

**问题2**应该也已经解决
